name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout and fetch submodule
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install asciidoctor
      run: |
        sudo apt-get update
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get -y install --no-install-recommends asciidoctor
    - name: Build the site
      run: |
        bash build.sh
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: "./output"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
